### ISSUE TITLE
Out of order EOF sequences

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-test-suite-generator#3]
Hi Ross
This new signature from the latest PRONOM batch doesn't seem to generate a proper test:
http://apps.nationalarchives.gov.uk/PRONOM/fmt/648

The issue is with this bit:

Position type   Absolute from EOF
Offset  8
Value   30333069

which isn't appearing in an absolute position from the EOF.

This seems a bit of a dodgy one anyway as the TNA's example "BOF: 030i (OFFSET 4) EOF: Svar (Offset 62) EOF: 030i (OFFSET 8)" doesn't conform to the signature because that "Svar" sequence should be between offset 20-46 from the EOF, not offset 62.

thanks!
Richard

**Comment by ross-spencer** [comment]
Fixed in DROID signature file v79. Leave as open for now as this might still crop up when creating skeleton files.
