### ISSUE TITLE
fmt/894 (v85)

### ISSUE THREAD

**Issue by richardlehane** [exponential-decay/skeleton-test-suite-generator#5]
Hi Ross
the second byte sequence in this signature is a "#" (hex 23). It should appear at an absolute offset from the BOF at 128. In yours it is at offset 170, appended to the end of the first byte sequence. This seems a bit like that EOF issue I reported: where you have two byte sequences that can overlay each other, rather than being adjacent.
Otherwise I'm passing all of yours for v85 (except fmt/899 and fmt/900 which you got errors printed for).
ta!
Rich

**Comment by ross-spencer** [comment]
Thanks Richard, I do need to sit down and investigate this some more. As
well as fmts 899/900 which I haven't an instinct as to why those two have
failed (the new PE signatures). But I'll set aside some time next week
hopefully and feed back some more information.

**Comment by richardlehane** [comment]
edit - not an absolute 128 offset for that "#", but a range 0-128. Issue still applies as it appears at offset 170 in the skeleton file

**Comment by ross-spencer** [comment]
Write-up of how to fix this here: https://github.com/digital-preservation/droid/issues/115#issuecomment-250342003

**Comment by ross-spencer** [comment]
Hmm, it's an odd signature with the two variable offsets for byte sequences one and two starting from offsets zero and one... http://www.nationalarchives.gov.uk/PRONOM/fmt/894

**Comment by richardlehane** [comment]
yes, I wonder what the rationale was? a very weird signature
